### ISSUE TITLE
Classic pebbles with Time firmware 3.x - blank menus

### ISSUE THREAD

**Issue by SpinyN0rman** [NitroG42/pebble-mytodoist#7]
Hi, I suspect this may be a simple one but haven't had a chance to look at the code. 

On my pebble steel (firmware 3.8.2) all the menus inside My Todoist are blank though still navigable, check out the video here: https://drive.google.com/file/d/0B4SYDi7wInDjY1BIaWRydDhISnM/view?usp=docslist_api

My guess is that the steel can't display the colours of the menus, so they just appear blank -just a guess though.

**Comment by NitroG42** [comment]
Detect aplit => https://github.com/pebble/pebblejs/issues/64

**Comment by NitroG42** [comment]
Can't be solved without changing the Basalt rendering.
Need to wait for Meiguro's fix : https://github.com/pebble/pebblejs/issues/126

**Comment by NitroG42** [comment]
Should work for now.
